version: "3.7"

services:
  db_keycloak:
    image: postgres:12.2
    container_name:  keycloak-Postgress
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "7001:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name:  keycloak-PgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "7002:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name:  keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db_keycloak
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: secret
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpass
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 7003:8080
    depends_on:
      - db_keycloak

volumes:
  db-data:
  pgadmin-data: